name: Auto Update EPG

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch New EPG XML
        run: |
          curl -o epg.xml "https://epg.pw/xmltv/epg_ALL.xml.gz"
          gunzip -f epg.xml.gz  # Extracts the file if it's compressed

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add epg.xml
          git commit -m "Auto-updated EPG" || exit 0
          git push
