name: Auto Update EPG

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Channel List
        run: |
          curl -o channels.txt "https://raw.githubusercontent.com/ragetraxx/epg-auto/main/formatted_channels.txt"
          cat channels.txt  # Debugging: print extracted channels

      - name: Download & Extract EPG Files
        run: |
          rm -f epg.xml.gz epg.xml merged_epg.xml  # Clean old files
          
          urls=(
            "https://epgshare01.online/epgshare01/epg_ripper_CA1.xml.gz"
            "https://epgshare01.online/epgshare01/epg_ripper_FANDUEL1.xml.gz"
            "https://epgshare01.online/epgshare01/epg_ripper_PH1.xml.gz"
            "https://epgshare01.online/epgshare01/epg_ripper_PH2.xml.gz"
            "https://epgshare01.online/epgshare01/epg_ripper_US1.xml.gz"
            "https://epgshare01.online/epgshare01/epg_ripper_US_LOCALS2.xml.gz"
            "https://epgshare01.online/epgshare01/epg_ripper_UK1.xml.gz"
            "https://epgshare01.online/epgshare01/epg_ripper_US_SPORTS1.xml.gz"
          )

          for url in "${urls[@]}"; do
            filename=$(basename "$url")
            curl -o "$filename" "$url"
            gunzip -f "$filename" || mv "$filename" "${filename%.gz}"
          done

          # Merge all EPG files
          cat *.xml > merged_epg.xml
          ls -lh merged_epg.xml  # Debugging: check file size

      - name: Extract Available EPG Channel IDs
        run: |
          grep '<channel id="' merged_epg.xml | awk -F'id="' '{print $2}' | awk -F'"' '{print $1}' > available_channels.txt
          cat available_channels.txt  # Print available EPG channel IDs

      - name: Compare Available Channels with Channel List
        run: |
          echo "Checking if listed channels exist in EPG..."
          grep -Ff channels.txt available_channels.txt || echo "Some channels are missing!"

      - name: Filter EPG XML to Keep Only Needed Channels
        run: |
          grep -Ff channels.txt merged_epg.xml > epg.xml || echo "No matching channels found!"
          ls -lh epg.xml  # Debugging: check file size
          head -n 50 epg.xml  # Print first few lines for verification

      - name: Upload EPG XML to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: epg.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
