name: Auto Update EPG

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  update-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch TV.m3u File
        run: |
          curl -o TV.m3u "https://raw.githubusercontent.com/ragetraxx/github.io/main/TV.m3u"

      - name: Extract Channel List
        run: |
          grep '^#EXTINF' TV.m3u | awk -F'tvg-id="' '{print $2}' | awk -F'"' '{print $1}' > channels.txt

      - name: Fetch EPG XML
        run: |
          curl -o epg.xml.gz "https://epgshare01.online/epgshare01/epg_ripper_ALL_SOURCES1.xml.gz"
          gunzip -f epg.xml.gz || mv epg.xml.gz epg.xml  # Extract if compressed

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add epg.xml channels.txt
          git commit -m "Auto-updated EPG" || exit 0
          git push
